# Generated by Django 2.2.1 on 2019-06-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fencers_management', '0003_auto_20190606_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('date', models.DateField(blank=True, verbose_name='Austragungsdatum')),
                ('ageclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fencers_management.AgeClass', verbose_name='Altersklasse')),
                ('participants', models.ManyToManyField(blank=True, to='fencers_management.Fencer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Tunier',
                'verbose_name_plural': 'Turniere',
            },
        ),
    ]
