# Generated by Django 2.2.3 on 2019-07-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fencers_management', '0003_auto_20190606_2306'),
        ('tournament_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Runde')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_management.Tournament', verbose_name='Tunier')),
            ],
            options={
                'verbose_name': 'Runde',
                'verbose_name_plural': 'Runden',
            },
        ),
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter1_points', models.IntegerField(verbose_name='Punkte Fechter 1')),
                ('fighter2_points', models.IntegerField(verbose_name='Punkte Fechter 2')),
                ('fighter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fencers_management.Fencer', verbose_name='Kämpfer 1')),
                ('fighter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fencers_management.Fencer', verbose_name='Kämpfer 2')),
                ('related_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_management.Round', verbose_name='Runde')),
            ],
            options={
                'verbose_name': 'Kampf',
                'verbose_name_plural': 'Kämpfe',
            },
        ),
    ]
