# Generated by Django 2.2.2 on 2019-07-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fencers_management', '0003_auto_20190606_2306'),
        ('tournament_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter1_points', models.IntegerField(verbose_name='Punkte Fechter 1')),
                ('fighter2_points', models.IntegerField(verbose_name='Punkte Fechter 2')),
                ('fighter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fencers_management.Fencer', verbose_name='Kämpfer 1')),
                ('fighter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fencers_management.Fencer', verbose_name='Kämpfer 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_management.Tournament', verbose_name='Tunier')),
            ],
            options={
                'verbose_name': 'Kampf',
                'verbose_name_plural': 'Kämpfe',
            },
        ),
    ]
