# Generated by Django 2.2.3 on 2019-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0002_combat_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Gesperrt'),
        ),
        migrations.AddField(
            model_name='round',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Gesperrt'),
        ),
    ]
