# Generated by Django 2.2.3 on 2019-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0003_auto_20190712_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='fighter1_points',
            field=models.IntegerField(blank=True, verbose_name='Punkte Fechter 1'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='fighter2_points',
            field=models.IntegerField(blank=True, verbose_name='Punkte Fechter 2'),
        ),
    ]
