# Generated by Django 2.2.3 on 2019-07-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fencers_management', '0003_auto_20190606_2306'),
        ('tournament_management', '0006_auto_20190716_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved', models.IntegerField(default=0, verbose_name='Erhaltene Treffer')),
                ('given', models.IntegerField(default=0, verbose_name='Gegebene Treffer')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('fencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fencers_management.Fencer', verbose_name='Fechter')),
                ('related_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_management.Round', verbose_name='Runde')),
            ],
            options={
                'verbose_name': 'Punkte',
                'verbose_name_plural': 'Punkte',
            },
        ),
    ]
