# Generated by Django 2.2.3 on 2019-07-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0007_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Siege'),
        ),
    ]
