# Generated by Django 2.2.1 on 2019-05-20 07:57

import OFTM2.apps.fencers_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=60, verbose_name='Nachname')),
                ('gender', models.IntegerField(choices=[(0, 'Männlich'), (1, 'Weiblich')], verbose_name='Geschlecht')),
                ('fechtpass', models.CharField(blank=True, max_length=9, unique=True, validators=[OFTM2.apps.fencers_management.validators.validate_fechtpass], verbose_name='Fechtpass Nummer')),
                ('birthday', models.DateField(verbose_name='Geburtsdatum')),
            ],
            options={
                'verbose_name': 'Fechter/in',
                'verbose_name_plural': 'Fechter/innen',
            },
        ),
    ]
