# Generated by Django 2.2.1 on 2019-05-20 10:01

from django.db import migrations, models
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fencers_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('startDate', partial_date.fields.PartialDateField(verbose_name='Anfangs Datum')),
                ('endDate', partial_date.fields.PartialDateField(verbose_name='End Datum')),
            ],
        ),
    ]
