# Generated by Django 2.2.1 on 2019-06-06 21:06

import datetime
from django.db import migrations, models
from OFTM2.apps.fencers_management.helpers import calculate_age


def convertToAge(apps, schema_editor):
    #Converts the date based ageclasses to age based
    ac = apps.get_model('fencers_management', 'ageclass')
    for ageclass in ac.objects.all():
        ageclass.startAge = int(calculate_age(ageclass.startDate))
        ageclass.endAge = int(calculate_age(ageclass.endDate))


class Migration(migrations.Migration):

    dependencies = [
        ('fencers_management', '0002_ageclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ageclass',
            options={'verbose_name': 'Altersklasse', 'verbose_name_plural': 'Altersklassen'},
        ),
        migrations.AddField(
            model_name='ageclass',
            name='endAge',
            field=models.IntegerField(verbose_name='End Alter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ageclass',
            name='startAge',
            field=models.IntegerField(verbose_name='Anfangs Alter'),
            preserve_default=False,
        ),
        migrations.RunPython(convertToAge),
        migrations.RemoveField(
            model_name='ageclass',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='ageclass',
            name='startDate',
        ),

    ]
