# Generated by Django 2.2.3 on 2019-07-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament_management', '0008_points_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('view', models.IntegerField(choices=[(0, 'Punkte'), (1, 'Kämpfe'), (2, 'Punkte und Kämpfe')], default=0, verbose_name='Anzeige')),
                ('last_reload', models.DateTimeField(verbose_name='Letzer Reload')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournament_management.Tournament', verbose_name='Tunier')),
            ],
            options={
                'verbose_name': 'Beamer',
                'verbose_name_plural': 'Beamer',
            },
        ),
    ]
